test/test_um2netcdf.py
umpost/um2netcdf.py

Fixes #34.
This change extracts heaviside pressure masking functionality to separate functions. I had to refactor & shrink the old logic to facilitate unit testing (otherwise hacky mocking code was required). I've also added a `cube_lookup` to begin simplifying cube ops in `process()` and making the workflow more pythonic.
Known gaps :
* Magic numbers
* Some vars/funcs need good names (some naming changes are "open" should someone think something)
* `process()` still lacks a test
For the review, any opinions on the restructure, gaps & logic correctness comments are welcome.

Refactor/extract heaviside functionality & add unit tests

---

test/test_um2netcdf.py
umpost/um2netcdf.py

Relates to #34.
The original solution added custom records to `cube` _global attributes_. These were written to `NetCDF` _global attributes_, "breaking" the compatibility of testing outputs. This solution introduces a slight hack, dynamically adding `item_code` as an attribute of each `cube` instead of in the `attributes` dict.
I've manually confirmed running `um2nc` no longer includes additional global vars.

Fix heaviside test regression

---

umpost/um2netcdf.py

Closes #42.
This PR extracts & updates the file history attribute. String formatting has been updated with modern Python, and the hard-coded filename has been removed.
Known problems:
* The new version number needs to be determined (the method should ideally be decided in this PR).

Extract history function

---

test/test_um2netcdf.py
umpost/um2netcdf.py

Closes #51. Also related to #14.
Several elements are included in this PR (which is larger than I'd prefer):
* Extracting cube renaming code to funcs
* Adding multiple test fixtures and unit tests
* Reordering some naming logic (this didn't break testing on my device)
Overall, this moves ~37 lines of code out from `process()`.
Gaps:
* `process()` still lacks a test, but is now only ~1 page of code
* Some mocks may not represent real object config, but I've tweaked variables to skip code segments & force specific code segments to execute
* A few code branches aren't covered by the tests, usually where there's a normal return from nothing happening
For the review, any opinions on the restructure, gaps & correctness checks are welcome!

Extract cube var renaming code to functions

---

test/test_um2netcdf.py
umpost/um2netcdf.py

Resolves #50 (also related to #14).
This is a fairly complicated PR around testing & refactoring the central `process()` workflow function in `um2netcdf/um2nc`.
This work is intended to provide initial testing & cleanup of `process()`, providing a framework to ensure the workflow is consistent over future refactoring steps.
**For background:**
* `um2nc` processes UM files, modifying variables & saving to NetCDF files
* The core `um2nc` driver is the `process()` workflow function (it's also the main API entry point)
* Commit 0 in this repo had no unit tests
* `process()` was initially 140 lines of processing logic & too difficult to unit test
* Recent work extracted blocks of functionality (e.g. variable renaming) to separate functions. This simplified & compressed `process()` to focus on …

Refactor process() testing & cleaning cube masking/filtering logic

---

test/test_um2netcdf.py
umpost/um2netcdf.py

This small PR adds tests to `fix_cell_methods()` & replaces old manual looping logic.
I haven't explicitly tested multiple cell methods in a `cube.cell_methods` attr. From examining the `aiihca.paa1jan.subset` data file, there's always only 1 cell method in the `cube.cell_methods` sequence for each cube.
Any comments on the new code style, correctness & gaps is welcome :-)

Test & refactor `fix_cell_methods()`

---

umpost/um2netcdf.py

Resolves #75. 
This is a quick PR to reorder `process()` into 3 chunks: input I/O, cube mods & output I/O. It is mainly to help readability & structure for retro-fixing `cubewrite()`.
The tests pass locally on my machine & a couple of command line tests show the outputs from this are still a binary match to the very 1st commit in this repo.
Comments welcome :-)

Refactor `process()` I/O / operation order

---

.github/workflows/CI.yml
pyproject.toml
umpost/conversion_driver_esm1p5.py

This PR addresses the ESM1.5 conversion driver part of #81, splitting the `main` block into separate `main()` and `parse_args()` functions, which allows for an entry point to be added to the `pytproject.toml` file. 
Adding entry points to `um2netcdf` will be addressed separately in #82. 
I'm unsure how to test that the entry point is working, and so suggestions on that would be great too!

Split main into separate function and add entry point

---

umpost/um2netcdf.py

This PR adds a `main()` function & entry point to `um2netcdf`. The unit tests pass on my system, as do some manual tests of the command line script to convert a test file.
Known Gaps:
* I skipped adding even a very basic unit test, although this can be addressed in future tidying work.
* Running a CI test of `um2netcdf --help` is missing from this. I can add it to this PR or push out to a smaller sub issue.

Add un2nc `main()` entry point

---

test/test_um2netcdf.py
umpost/um2netcdf.py

Closes #53. Note, this PR is merges to `main`.
This PR:
* adds unit tests for `fix_level_coord()`
* moves the function down to call order (i.e. below `process()`)
* Cleans the code slightly
These tests use `iris` coordinate objects to avoid mocks cube attributes. Based on this experiment, this could be a reasonable approach for other tests requiring `iris` coordinates.

Add tests/clean `fix_level_coord()`

---

test/test_um2netcdf.py
umpost/um2netcdf.py

Resolves #95.
This PR is mostly to extract & test 64 to 32 bit down-conversion from `cubewrite()`.
I've added a few things:
* New `data` member to `DummyCube`, so data grids can be attached to imitation cubes (it's simpler to reuse fixtures).
* Unit tests
* Added integer overflow warning (just in case)
I'll defer moving this step into `process()` until `cubewrite()` is deconstructed.
Comments welcome :-)

Clean, test & refactor 64 to 32 bit conversion step.

---

test/test_um2netcdf.py

Closes #110.
This PR merges `DummyCube` & `DummyCubeWithCoords` into a single object to simulate `cubes`. The goal is to refactor & simplify test objects, working towards having one obvious class to use for `cubes`.
Bonus: fixed some white space.

Refactor: merge `DummyCube` & `DummyCubeWithCoords`

---

test/test_um2netcdf.py
umpost/um2netcdf.py

This closes #69.
This PR covers multiple elements to switch tests to using `DummyCube`:
* Replaces several `Mock` objs masquerading as cubes with `DummyCube`
* Removes old setup cruft
* Cleans some test fixtures
* Adds coords to other test fixtures (fixtures better open for reuse)
* Removes `mock.patch("umpost.um2netcdf.fix_latlon_coords")` in `process()` tests
* BONUS: removes `mock.patch("umpost.um2netcdf.fix_level_coord")` in `process()` tests

Refactor cube testing objects/mocking with `DummyCube`

---

test/test_um2netcdf.py
umpost/um2netcdf.py

Closes #98 (see issue for reasoning).
This PR is intended to:
* Remove some old tests that are now irrelevant
* Refine `set_item_codes()` to remove spurious warning (clean test output)
* Add some docs...
Comments welcome!

Fix `set_item_codes()` & remove old tests

---

test/test_um2netcdf.py

Closes #120.
This micro PR fixes some minor problems:
* Instantiate `self.attributes` properly if `attributes=None`
* Update, don't overwrite `self.attributes`
* Improve attribute order / readability
* Improve comments

Fix `DummyCube` initialisation

---

umpost/um2netcdf.py

Closes #126 
This PR adds a warning filter around the `mule.load_umfile()` call in `process`, in order to hide warnings about missing STASHmaster files. The information in these files is not used in `um2nc` and hence these warnings aren't too relevant.
I aded the filter directly in `process` to try and keep it localised, however this does add slightly more code to `process`. Any suggested changes or ideas are welcome!

Prevent mule missing STASHmaster warnings

---

test/test_um2netcdf.py

Closes #128.
This PR covers a few things:
* Decouples the simple int conversion case from the parameter generated overflow testing
* Moves the basic condition to its own test
* Captures overflow warnings to keep test output clean

Capture 32 bit overflow warnings in tests.

---

test/test_um2netcdf.py
umpost/um2netcdf.py

Closes #135 .
This PR provides a warning type & captures cube drop warnings to keep test output clean.

Capture & test cube dropping warnings in `test_process()`

---

test/test_um2netcdf.py
umpost/um2netcdf.py

First step to doing #100.
This PR is intended for facilitating testing functionality for fixing the forecast reference time.
As of late Sept 2024, work up to commit fd664c7b only provides a skeleton of unit tests. It doesn't meaningfully test any cube time changes. This PR includes some skipped tests as the testing required is unclear.
Work on this PR needs to answer & address the following:
These questions will help determine what work is required. Any comments/ideas welcome!
Fixing & testing this function is specified in #141.

Extract forecast reference time

---

test/test_um2netcdf.py
umpost/um2netcdf.py

Closes #99 and continues on from (unmerged) work in #114.
This PR extracts the fill value modifications from `cubewrite()` into two functions: `get_default_fill_value()` which gets the default fill value for a cube's data type, and `fix_fill_value()` which sets a cube's `missing_value` attribute.

Extract fill value fixes from `cubewrite()`

---

umpost/um2netcdf.py

Closes #142.
This PR covers refactoring: extracting the time coord fix function & decoupling from the file I/O write process. Tests are intended for work on #143. I've tested this with the [binary diff script](https://github.com/ACCESS-NRI/um2nc-standalone/blob/main/integration/binary_diff.sh).
This is a step closer to combining `process()` and `cubewrite()` for a single workflow function to rule them all.

Extract time coord dimension fix

---

test/test_conversion_driver_esm1p5.py
umpost/conversion_driver_esm1p5.py

This PR closes #124 
It adds a new step to the `convert_esm1p5_output_dir` function, where pairs of `(input_path, output_path)` tuples are removed prior to the conversion step if their `output_path`s are not unique, and warns the user when this occurs.

Guard against ESM1.5 file naming collisions

---

test/test_um2netcdf.py

The branch [145/fcis-architecture](https://github.com/ACCESS-NRI/um2nc-standalone/tree/145-fcis-fix-process-tests) implements the big restructure of the `process` and `cubewrite` functions, as described in #145. The main changes are:
- IO steps are handled in `process()`, while all cube modification steps are moved to a new `process_cubes()` function. 
- The new `process_cubes()` function absorbs any cube modification steps previously part of `cubewrite()`.
Roughly `process()` becomes the "imperative shell", performing all the reading and writing, while `process_cubes()` forms the "functional core", performing cube modifications over several modular steps.
The new structure caused the existing end to end tests of `process()` to break. This PR follows on from work in the branch …

Fix tests of process to work with the new FCIS restructure

---

test/test_conversion_driver_esm1p5.py
umpost/conversion_driver_esm1p5.py

Closes #137 
This PR captures the unknown file name key warning produced by `get_nc_filename()` and tests that it occurs in `test_get_nc_write_path_unrecognized_unit()`.

Capture filename key warning in test

---

pyproject.toml
test/test_um2netcdf.py
umpost/um2netcdf.py

This PR closes the main section of #145. Remaining tasks will be split off into smaller issues.
This finishes off the implementation of the FCIS architecture, where IO steps are all separated into an "imperative shell", and all cube modifications are handled in the "functional core" `process_cubes()` function, making the main parts of the code testable. 
These changes were put together over a couple of smaller steps into the feature branch `145/fcis-architecture`, and the purpose of this PR is to bring the changes into `main` - hence the changes may look familiar!
The changes to `um2netcdf.py` include: 
- Moving any cube modification steps from `cubewrite()` into `process_cubes()`
- Move any IO from `cubewrite()` into `process()`
- `cubewrite()` is then deleted.
The changes to …

Swap to FCIS architecture

---

README.md
src/um2nc/conversion_driver_esm1p5.py
src/um2nc/um2netcdf.py

This PR closes #164. It adds basic usage instructions to the `README.md` file, outlining the available commands and options.
It also modifies the `argparse` help strings for clarity and grammatical consistency.
Any suggestions or feedback for making the documentation clearer or more informative would be very welcome!

Add basic usage instructions to README

---

integration/INTEGRATION_README.md
integration/regression_tests.sh

Closes #117. This pull request updates the paths for the regression test data to match its location on gadi.

Update paths to regression test data

---

.conda/meta.yaml
.github/workflows/CD.yml

Updated `CD.yml` to build and upload to Anaconda.org packages for any platform. Reintroduced the use of the updated ['uibcdf/action-build-and-upload-conda-packages'](https://github.com/uibcdf/action-build-and-upload-conda-packages) action for building and uploading conda packages.

Updated CD

---

.conda/conda_build_config.yaml

New versions of conda can build packages having 2 different extensions:
- `.tar.bz2`
- `.conda`
The `.conda` extension is a fairly new one. 
I think it would be best if we enforce the production of `.tar.bz2` to attach to our releases (as these files are more commonly used). To do so, the `conda_build_config.yaml` file has been added with a related field that enables that.
Also, this will fix the issue with the current error with the [release CD](https://github.com/ACCESS-NRI/um2nc-standalone/actions/runs/12858703930/job/35848192545) that is trying to build a [`.conda` package](https://github.com/ACCESS-NRI/um2nc-standalone/actions/runs/12858703930/job/35848192545#step:4:166), but the [uibcdf/action-build-and-upload-conda-packages](https://github.com/uibcdf/action-build-and-upload-conda-pa …

Added conda_build_config to force the production of 'tar.bz2' packages

---

.github/workflows/CD.yml

Fix errors in the build

---

.github/workflows/CD.yml

Another fix for the `CD.yml` release workflow:

Added label to the 'uibcdf/action-build-and-upload-conda-packages' action

---

.github/workflows/CD.yml

Fix CD release
